// todomvc-vue/src/TodoCompleteCheckbox.vue
<script lang="ts" setup>
import type { TodoT } from "../../src/global";
import { inject } from "./context";

const { todo, checkboxId } = defineProps<{
  todo: TodoT;
  checkboxId: string;
}>();

const { completeTodo } = inject("useActions")();
const onKeyup = (e: any) => {
  if (e.key === "Enter") {
    const checkbox = e.currentTarget as HTMLInputElement;
    completeTodo(todo.id, !checkbox.checked);
  }
};
</script>

<template>
  <input
    type="checkbox"
    :id="checkboxId"
    class="checkbox checkbox-lg mr-2 self-center"
    :aria-label="`할일 ${todo.content}을 완료하시려면 클릭하세요.`"
    :checked="todo.isCompleted"
    @change="(e) => {completeTodo(todo.id, (e.currentTarget as HTMLInputElement).checked)}"
    @keyup="onKeyup"
  />
</template>

// todomvc-svelte/src/TodoCompleteCheckbox.svelte
<script lang="ts">
  import type { TodoT } from "../../src/global";

  import { inject } from "./context";

  export let todo: TodoT;
  export let checkboxId: string;

  const { completeTodo } = inject("actions");
</script>

<input
  id={checkboxId}
  type="checkbox"
  class="checkbox checkbox-lg mr-2 self-center"
  aria-label={`할일 ${todo.content}을 완료하시려면 클릭하세요.`}
  checked={todo.isCompleted}
  on:keyup={(e) => {
    if (e.key === "Enter") {
      const checkbox = e.currentTarget;
      completeTodo(todo.id, !checkbox.checked);
    }
  }}
  on:change={(e) => completeTodo(todo.id, e.currentTarget.checked)}
/>
