// todomvc-svelte/src/App.svelte
<script lang="ts">
  import { getTodoListStore } from "@/context";
  import TodoForm from "@/TodoForm.svelte";
  import TodoItem from "@/TodoItem.svelte";

  const todoList = getTodoListStore();
</script>

<div class="card shadow-lg rounded-2xl p-4 max-w-lg">
  <TodoForm />
  <ul>
    {#each $todoList || [] as todo (todo.id)}
      <TodoItem {todo} />
    {/each}
  </ul>
</div>

// todomvc-react/src/App.tsx
import React from "react";
import TodoForm from "@/TodoForm";
import TodoItem from "@/TodoItem";
import { useTodoList } from "@/useTodoList";

export default function App() {
  const { todoList } = useTodoList();

  return (
    <div className="card shadow-lg rounded-2xl p-4 max-w-lg">
      <TodoForm />
      <ul>
        {todoList.map((todo) => (
          <TodoItem key={todo.id} todo={todo} />
        ))}
      </ul>
    </div>
  );
}
