// todomvc-svelte/src/TodoItem.svelte
<script lang="ts">
  import type { TodoT } from "../../src/global";

  import { inject } from "./context";
  import TodoCompleteCheckbox from "./TodoCompleteCheckbox.svelte";
  import TodoDeleteButton from "./TodoDeleteButton.svelte";
  import TodoEditingForm from "./TodoEditingForm.svelte";

  export let todo: TodoT;
  const { deleteTodo } = inject("actions");

  const checkboxId = "todo-checkbox-" + todo.id;
</script>

<li
  class="mt-1 flex align-middle "
  on:keyup={(e) => {
    if (e.key === "Delete") deleteTodo(todo.id);
  }}
>
  <TodoCompleteCheckbox {todo} {checkboxId} />
  <TodoEditingForm {todo} {checkboxId} />
  <TodoDeleteButton {todo} />
</li>

// todomvc-react/src/TodoItem.tsx
import React from "react";
import type { TodoT } from "../../src/global";
import { inject } from "./context";
import TodoCompleteCheckbox from "./TodoCompleteCheckbox";
import TodoDeleteButton from "./TodoDeleteButton";
import TodoEditingForm from "./TodoEditingForm";

interface TodoItemProps {
  todo: TodoT;
}

export default function TodoItem({ todo }: TodoItemProps) {
  const { deleteTodo } = inject("useActions")();

  const checkboxId = "todo-checkbox-" + todo.id;
  return (
    <li
      className="mt-1 flex align-middle "
      onKeyUp={(e) => {
        if (e.key === "Delete") deleteTodo(todo.id);
      }}
    >
      <TodoCompleteCheckbox checkboxId={checkboxId} todo={todo} />
      <TodoEditingForm checkboxId={checkboxId} todo={todo} />
      <TodoDeleteButton todo={todo} />
    </li>
  );
}
